name: CI

on:
  push:
    branches:
    - main
    
jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
    
    - name: Run make hello command
      run: |
        make hello
    
