name: CI

on:
  push:
    branches:
    - main
    
jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Run make hello command
      run: make hello    
    - name: Test with pytest
      run: |
        make test
    
